### PR TITLE
Manage Defines for Embed attributes

### LINKED ISSUE #147: Manage Defines for Embed attributes
Hi,
I would like to use a Define compilation variable as source of an Embed meta tag like that : 

```as
[Embed(source=EMBED::my_logo, mimeType="image/png")]
```

With that I can define the path to the embed asset in the config file and use differents ones depending on the config file I use.

I've tried te understand where to manage the use of Defines in MetaTag, but the parsing/compile process is a bit complex. I'm looking at the BaseASParser class but I think it's a bit late in the process.

Can anyone help me to understand what to change to handle that.

Thanks !

### PR DESCRIPTION
**Pull request by taorepoara**
Resolves #147

### CODE REVIEW

**Comment by carlosrovira** [comment]
Hi @taorepoara, maybe @aharui or @joshtynjala could take a look of this PR.
I understand that you'r making it working for SWF target only, and with you changes now we can use "Embed" metadata?
Thanks for working on it

**Comment by taorepoara** [comment]
I made the change for the ActionScript parser only, but I think it can be use for every target. I'll check that. 

The "Embed" metadata was already available, but now compile time constants can be use as attribute value. 

I'm using it to manage the path of an Embed element to use it as Worker. If I build in debug mode I use the debug swf, else I use the release one.

**Comment by carlosrovira** [comment]
ok. two questions:
1.- did you build all 3 repos with tests to ensure all is ok
2.- also, can you provide some example code so people trying your PR can test your changes?
(for this you can add to the PR)
In that way I can do the check
Thanks in advance

**Comment by taorepoara** [comment]
I always have problem building the repos even using the Apache repos.

**Comment by taorepoara** [comment]
Here are two projects :
[examples.tar.gz](https://github.com/apache/royale-compiler/files/4574461/examples.tar.gz)

I can't test them because I don't use the royale-asjs project to build my projects (since I can't build it), only the compiler and typedefs. The embed-worker project work with my compilation way and the changes I made in this RP.

**Comment by carlosrovira** [comment]
He bajado el patch a mi local y he probado a añadir una variable como la de tu ejemplo y todo parece ok.

**Pull request merged**
