### PR TITLE
Add support for AIR SDK 50 language features

### LINKED ISSUE #219: Support for new AIR 50 SDK AS3 language features
The new AIR 50 Beta SDK introduces support for null-conditional operators, nullish coalescing and verbatim strings, outlined here https://github.com/airsdk/Adobe-Runtime-Support/discussions/1699#discussioncomment-3653584 😁

> - null-conditional operators
>   You can now write `val = obj?.prop;` as a shorthand for `val = (obj == null) ? null : obj.prop;`
> - nullish coalescing
>   You can now write `val = x ?? y;` as a shorthand for `val = (x != null) ? x : y;`
> - verbatim strings
>   You can now define a string with an `@` symbol at the start and then you don't need to escape backslashes.. eg. `@"c:\users\test.txt"`

### PR DESCRIPTION
**Pull request by piepie62**
Fixes #219 by adding the requested features

### CODE REVIEW

**Comment by Harbs** [comment]
Does this implement JS output? Is there tests for that?

(A quick browse at the code changes does not seem like it.)

**Comment by piepie62** [comment]
Having just looked at that portion of the code, I honestly don't think I know enough JavaScript to do this in a way that's not subtly incorrect. There are so many exceptions there that I have no idea what their purpose is that I think it would be best for someone that actually uses the language to build that part, instead of me

**Comment by Harbs** [comment]
No worries. Thanks for this!

@joshtynjala Do you have time to review this PR? You're probably the best one to do it.

**Comment by joshtynjala** [comment]
I have null conditional and nullish coalescing implemented locally (working in both SWF and JS), which I was planning to push soon, after I write some tests. I'll keep this PR in mind as I proceed.

**Comment by joshtynjala** [comment]
New language features are committed. I included the verbatim string implementation from this PR, with some additional commits to fix some bugs.

**Pull request closed without merging**
