### PR TITLE
Works on given test case. Hope I didn't break anything.

### PR DESCRIPTION
**Pull request by yishayw**
Reference #143

### CODE REVIEW

**Comment by greg-dove** [comment]
I just saw this review request yishay, I had already replied to the commit email with a couple of quick suggestions. I will try to look at this in more detail tonight my time.
Here's what I added via email:
-You might find a place in the code where there is something already that has 'needClosure' logic, but the logic that sets it to true does not yet include the specific case you are dealing with.
-Take a look at emitClosureStart and emitClosureEnd I think those will help out. 

(The second one is likely not needed if the first one is a solution, but these are just clues to help you better understand the compiler code, not any recommendation about the way to do what you are specifically working to fix - I have not looked into it yet)

**Comment by yishayw** [comment]
Hi,

Changing to
                                                emitClosureStart();
                                                emitAssignedValue(assignedNode);
                                                MemberAccessExpressionNode maenode = (MemberAccessExpressionNode)assignedNode;
                                                emitClosureEnd(maenode.getLeftOperandNode(), definition);

Results in

  org.apache.royale.utils.Language.as(c, MyButton).clickFunction = org.apache.royale.utils.Language.closure(this.parentApplication.buttonFunction, 'Function');

Which fails with

TypeError: Object.defineProperty called on non-object
Watch
Call Stack
org.apache.royale.utils.Language.closure
Language.js:281
MyBox.addElement
MyBox.js:39

**Comment by yishayw** [comment]
The problem is that my code is in JSEmitter which descends from JSRoyaleEmitter which overrides JSGoogEmitter.emitClosureStart(). I'm not sure there's a clean way to reuse the latter function.

If you do think of something let me know. Need to sign off...
Thanks.

**Comment by greg-dove** [comment]
Sorry I did not find time last night to check that. I see what you mean about the inheritance levels. There is some code in JSEmitter which I added which likely needs to be added to an overridden method in JSRoyaleEmitter. I will try to look into that this coming weekend.

What you might consider is overriding 'emitAssignedValue' in JSRoyaleEmitter and try adding the check in there, make the changes if necessary, and call the super method otherwise.
You should also check it is not a static function you are assigning,  and avoid doing anything special in that case, I think.

I will try to more time to look more tonight.

**Comment by yishayw** [comment]
This can be achieved in a more elegant way if the application source code is modified to make the function source explicit.

**Pull request closed without merging**
